<script src="<?=base_url()?>assets/js/jquery-3.6.0.min.js"></script>
<script src="<?=base_url()?>assets/js/bootstrap.bundle.min.js"></script>
<script src="<?=base_url()?>assets/js/jquery.magnific-popup.min.js"></script>
<script src="<?=base_url()?>assets/js/swiper-bundle.min.js"></script>
<script src="<?=base_url()?>assets/js/counter.js"></script>
<script src="<?=base_url()?>assets/js/typed.js"></script>
<script src="<?=base_url()?>assets/js/mixitup.min.js"></script>
<script src="<?=base_url()?>assets/js/progressbar.js"></script>
<script src="<?=base_url()?>assets/js/gsap.min.js"></script>
<script src="<?=base_url()?>assets/js/ScrollSmoother.min.js"></script>
<script src="<?=base_url()?>assets/js/ScrollToPlugin.min.js"></script>
<script src="<?=base_url()?>assets/js/ScrollTrigger.min.js"></script>
<script src="<?=base_url()?>assets/js/SplitText.min.js"></script>
<script src="<?=base_url()?>assets/js/TweenMax.min.js"></script>
<script src="<?=base_url()?>assets/js/jquery.meanmenu.min.js"></script>
<script src="<?=base_url()?>assets/js/tilt.jquery.min.js"></script>
<script src="<?=base_url()?>assets/js/beforeafter.jquery-1.0.0.min.js"></script>
<script src="<?=base_url()?>assets/js/basictable.min.js"></script>
<script src="<?=base_url()?>assets/js/backToTop.js"></script>
<script src="<?=base_url()?>assets/js/main.js"></script>
<script src="<?=base_url()?>assets/js/error-handling.js"></script>
<script src="<?=base_url()?>assets/js/offcanvas.js"></script>
<script src="<?=base_url()?>assets/js/wc-cursor.js"></script>